version: '3.7'
services:
  init-kafka:
    image: confluentinc/cp-kafka:latest
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list

      echo -e 'Deleting kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic stock-update-request-topic-name --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic stock-update-response-topic-name --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic stock-subtract-request-topic-name --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:9092 --topic stock-subtract-response-topic-name --delete --if-exists

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic stock-update-request-topic-name --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic stock-update-response-topic-name --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic stock-subtract-request-topic-name --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic stock-subtract-response-topic-name --replication-factor 3 --partitions 3


      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list
      "
    networks:
      - zielona