/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.kafka.stock.take.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum StockTakeStatus implements org.apache.avro.generic.GenericEnumSymbol<StockTakeStatus> {
  PENDING, REJECTED, ACCEPTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"StockTakeStatus\",\"namespace\":\"org.example.kafka.stock.take.avro.model\",\"symbols\":[\"PENDING\",\"REJECTED\",\"ACCEPTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
