server:
  port: 8103

logging:
  level:
    org.example: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/zielona
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres