/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.kafka.stock.sale.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SaleItem extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7304300389261657657L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SaleItem\",\"namespace\":\"org.example.kafka.stock.sale.avro.model\",\"fields\":[{\"name\":\"menuItemId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"quantity\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SaleItem> ENCODER =
      new BinaryMessageEncoder<SaleItem>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SaleItem> DECODER =
      new BinaryMessageDecoder<SaleItem>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SaleItem> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SaleItem> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SaleItem> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SaleItem>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SaleItem to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SaleItem from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SaleItem instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SaleItem fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String menuItemId;
  private long quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SaleItem() {}

  /**
   * All-args constructor.
   * @param menuItemId The new value for menuItemId
   * @param quantity The new value for quantity
   */
  public SaleItem(java.lang.String menuItemId, java.lang.Long quantity) {
    this.menuItemId = menuItemId;
    this.quantity = quantity;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return menuItemId;
    case 1: return quantity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: menuItemId = value$ != null ? value$.toString() : null; break;
    case 1: quantity = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'menuItemId' field.
   * @return The value of the 'menuItemId' field.
   */
  public java.lang.String getMenuItemId() {
    return menuItemId;
  }


  /**
   * Sets the value of the 'menuItemId' field.
   * @param value the value to set.
   */
  public void setMenuItemId(java.lang.String value) {
    this.menuItemId = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public long getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(long value) {
    this.quantity = value;
  }

  /**
   * Creates a new SaleItem RecordBuilder.
   * @return A new SaleItem RecordBuilder
   */
  public static org.example.kafka.stock.sale.avro.model.SaleItem.Builder newBuilder() {
    return new org.example.kafka.stock.sale.avro.model.SaleItem.Builder();
  }

  /**
   * Creates a new SaleItem RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SaleItem RecordBuilder
   */
  public static org.example.kafka.stock.sale.avro.model.SaleItem.Builder newBuilder(org.example.kafka.stock.sale.avro.model.SaleItem.Builder other) {
    if (other == null) {
      return new org.example.kafka.stock.sale.avro.model.SaleItem.Builder();
    } else {
      return new org.example.kafka.stock.sale.avro.model.SaleItem.Builder(other);
    }
  }

  /**
   * Creates a new SaleItem RecordBuilder by copying an existing SaleItem instance.
   * @param other The existing instance to copy.
   * @return A new SaleItem RecordBuilder
   */
  public static org.example.kafka.stock.sale.avro.model.SaleItem.Builder newBuilder(org.example.kafka.stock.sale.avro.model.SaleItem other) {
    if (other == null) {
      return new org.example.kafka.stock.sale.avro.model.SaleItem.Builder();
    } else {
      return new org.example.kafka.stock.sale.avro.model.SaleItem.Builder(other);
    }
  }

  /**
   * RecordBuilder for SaleItem instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SaleItem>
    implements org.apache.avro.data.RecordBuilder<SaleItem> {

    private java.lang.String menuItemId;
    private long quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.kafka.stock.sale.avro.model.SaleItem.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.menuItemId)) {
        this.menuItemId = data().deepCopy(fields()[0].schema(), other.menuItemId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing SaleItem instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.kafka.stock.sale.avro.model.SaleItem other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.menuItemId)) {
        this.menuItemId = data().deepCopy(fields()[0].schema(), other.menuItemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'menuItemId' field.
      * @return The value.
      */
    public java.lang.String getMenuItemId() {
      return menuItemId;
    }


    /**
      * Sets the value of the 'menuItemId' field.
      * @param value The value of 'menuItemId'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.SaleItem.Builder setMenuItemId(java.lang.String value) {
      validate(fields()[0], value);
      this.menuItemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'menuItemId' field has been set.
      * @return True if the 'menuItemId' field has been set, false otherwise.
      */
    public boolean hasMenuItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'menuItemId' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.SaleItem.Builder clearMenuItemId() {
      menuItemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public long getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.SaleItem.Builder setQuantity(long value) {
      validate(fields()[1], value);
      this.quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.SaleItem.Builder clearQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SaleItem build() {
      try {
        SaleItem record = new SaleItem();
        record.menuItemId = fieldSetFlags()[0] ? this.menuItemId : (java.lang.String) defaultValue(fields()[0]);
        record.quantity = fieldSetFlags()[1] ? this.quantity : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SaleItem>
    WRITER$ = (org.apache.avro.io.DatumWriter<SaleItem>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SaleItem>
    READER$ = (org.apache.avro.io.DatumReader<SaleItem>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










