/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.kafka.stock.sale.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum SaleStatus implements org.apache.avro.generic.GenericEnumSymbol<SaleStatus> {
  PENDING, PAID, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SaleStatus\",\"namespace\":\"org.example.kafka.stock.sale.avro.model\",\"symbols\":[\"PENDING\",\"PAID\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
