/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.kafka.stock.sale.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StockDeduceRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 602810792496909137L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockDeduceRequestAvroModel\",\"namespace\":\"org.example.kafka.stock.sale.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"date\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"saleId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"saleStatus\",\"type\":{\"type\":\"enum\",\"name\":\"SaleStatus\",\"symbols\":[\"PENDING\",\"PAID\",\"CANCELLED\"]}},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SaleItem\",\"fields\":[{\"name\":\"menuItemId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"quantity\",\"type\":\"long\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<StockDeduceRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<StockDeduceRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockDeduceRequestAvroModel> DECODER =
      new BinaryMessageDecoder<StockDeduceRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockDeduceRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockDeduceRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockDeduceRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<StockDeduceRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockDeduceRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockDeduceRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockDeduceRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockDeduceRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String sagaId;
  private java.time.Instant createdAt;
  private java.time.Instant date;
  private java.lang.String saleId;
  private org.example.kafka.stock.sale.avro.model.SaleStatus saleStatus;
  private java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockDeduceRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sagaId The new value for sagaId
   * @param createdAt The new value for createdAt
   * @param date The new value for date
   * @param saleId The new value for saleId
   * @param saleStatus The new value for saleStatus
   * @param items The new value for items
   */
  public StockDeduceRequestAvroModel(java.lang.String id, java.lang.String sagaId, java.time.Instant createdAt, java.time.Instant date, java.lang.String saleId, org.example.kafka.stock.sale.avro.model.SaleStatus saleStatus, java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem> items) {
    this.id = id;
    this.sagaId = sagaId;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.date = date.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.saleId = saleId;
    this.saleStatus = saleStatus;
    this.items = items;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sagaId;
    case 2: return createdAt;
    case 3: return date;
    case 4: return saleId;
    case 5: return saleStatus;
    case 6: return items;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: sagaId = value$ != null ? value$.toString() : null; break;
    case 2: createdAt = (java.time.Instant)value$; break;
    case 3: date = (java.time.Instant)value$; break;
    case 4: saleId = value$ != null ? value$.toString() : null; break;
    case 5: saleStatus = (org.example.kafka.stock.sale.avro.model.SaleStatus)value$; break;
    case 6: items = (java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.lang.String getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.lang.String value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.time.Instant getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.time.Instant value) {
    this.date = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'saleId' field.
   * @return The value of the 'saleId' field.
   */
  public java.lang.String getSaleId() {
    return saleId;
  }


  /**
   * Sets the value of the 'saleId' field.
   * @param value the value to set.
   */
  public void setSaleId(java.lang.String value) {
    this.saleId = value;
  }

  /**
   * Gets the value of the 'saleStatus' field.
   * @return The value of the 'saleStatus' field.
   */
  public org.example.kafka.stock.sale.avro.model.SaleStatus getSaleStatus() {
    return saleStatus;
  }


  /**
   * Sets the value of the 'saleStatus' field.
   * @param value the value to set.
   */
  public void setSaleStatus(org.example.kafka.stock.sale.avro.model.SaleStatus value) {
    this.saleStatus = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem> getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem> value) {
    this.items = value;
  }

  /**
   * Creates a new StockDeduceRequestAvroModel RecordBuilder.
   * @return A new StockDeduceRequestAvroModel RecordBuilder
   */
  public static org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder newBuilder() {
    return new org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder();
  }

  /**
   * Creates a new StockDeduceRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockDeduceRequestAvroModel RecordBuilder
   */
  public static org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder newBuilder(org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder other) {
    if (other == null) {
      return new org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder();
    } else {
      return new org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new StockDeduceRequestAvroModel RecordBuilder by copying an existing StockDeduceRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new StockDeduceRequestAvroModel RecordBuilder
   */
  public static org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder newBuilder(org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel other) {
    if (other == null) {
      return new org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder();
    } else {
      return new org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockDeduceRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockDeduceRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<StockDeduceRequestAvroModel> {

    private java.lang.String id;
    private java.lang.String sagaId;
    private java.time.Instant createdAt;
    private java.time.Instant date;
    private java.lang.String saleId;
    private org.example.kafka.stock.sale.avro.model.SaleStatus saleStatus;
    private java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.date)) {
        this.date = data().deepCopy(fields()[3].schema(), other.date);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.saleId)) {
        this.saleId = data().deepCopy(fields()[4].schema(), other.saleId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.saleStatus)) {
        this.saleStatus = data().deepCopy(fields()[5].schema(), other.saleStatus);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.items)) {
        this.items = data().deepCopy(fields()[6].schema(), other.items);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing StockDeduceRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.date)) {
        this.date = data().deepCopy(fields()[3].schema(), other.date);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.saleId)) {
        this.saleId = data().deepCopy(fields()[4].schema(), other.saleId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.saleStatus)) {
        this.saleStatus = data().deepCopy(fields()[5].schema(), other.saleStatus);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.items)) {
        this.items = data().deepCopy(fields()[6].schema(), other.items);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.lang.String getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder setSagaId(java.lang.String value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[2], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.time.Instant getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder setDate(java.time.Instant value) {
      validate(fields()[3], value);
      this.date = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder clearDate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'saleId' field.
      * @return The value.
      */
    public java.lang.String getSaleId() {
      return saleId;
    }


    /**
      * Sets the value of the 'saleId' field.
      * @param value The value of 'saleId'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder setSaleId(java.lang.String value) {
      validate(fields()[4], value);
      this.saleId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'saleId' field has been set.
      * @return True if the 'saleId' field has been set, false otherwise.
      */
    public boolean hasSaleId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'saleId' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder clearSaleId() {
      saleId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'saleStatus' field.
      * @return The value.
      */
    public org.example.kafka.stock.sale.avro.model.SaleStatus getSaleStatus() {
      return saleStatus;
    }


    /**
      * Sets the value of the 'saleStatus' field.
      * @param value The value of 'saleStatus'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder setSaleStatus(org.example.kafka.stock.sale.avro.model.SaleStatus value) {
      validate(fields()[5], value);
      this.saleStatus = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'saleStatus' field has been set.
      * @return True if the 'saleStatus' field has been set, false otherwise.
      */
    public boolean hasSaleStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'saleStatus' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder clearSaleStatus() {
      saleStatus = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem> getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder setItems(java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem> value) {
      validate(fields()[6], value);
      this.items = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public org.example.kafka.stock.sale.avro.model.StockDeduceRequestAvroModel.Builder clearItems() {
      items = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockDeduceRequestAvroModel build() {
      try {
        StockDeduceRequestAvroModel record = new StockDeduceRequestAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.lang.String) defaultValue(fields()[1]);
        record.createdAt = fieldSetFlags()[2] ? this.createdAt : (java.time.Instant) defaultValue(fields()[2]);
        record.date = fieldSetFlags()[3] ? this.date : (java.time.Instant) defaultValue(fields()[3]);
        record.saleId = fieldSetFlags()[4] ? this.saleId : (java.lang.String) defaultValue(fields()[4]);
        record.saleStatus = fieldSetFlags()[5] ? this.saleStatus : (org.example.kafka.stock.sale.avro.model.SaleStatus) defaultValue(fields()[5]);
        record.items = fieldSetFlags()[6] ? this.items : (java.util.List<org.example.kafka.stock.sale.avro.model.SaleItem>) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockDeduceRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockDeduceRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockDeduceRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<StockDeduceRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










